definitions:
  response.BodyTpl:
    properties:
      errors: {}
      message:
        type: string
      status:
        type: string
      values: {}
    type: object
  response.Object:
    type: object
  users.LoginRequest:
    properties:
      password:
        type: string
      phone:
        type: string
    required:
    - password
    - phone
    type: object
  users.RegisterRequest:
    properties:
      name:
        type: string
      phone:
        type: string
      role:
        type: string
      username:
        type: string
    required:
    - name
    - phone
    - role
    - username
    type: object
info:
  contact: {}
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: To login user
      parameters:
      - description: payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/users.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.BodyTpl'
            - properties:
                message:
                  type: string
                status:
                  type: string
                values:
                  $ref: '#/definitions/response.Object'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/response.BodyTpl'
            - properties:
                errors:
                  $ref: '#/definitions/response.Object'
                message:
                  type: string
                status:
                  type: string
              type: object
      tags:
      - Login
  /auth/login-check:
    get:
      consumes:
      - application/json
      description: To check login user
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.BodyTpl'
            - properties:
                message:
                  type: string
                status:
                  type: string
                values:
                  $ref: '#/definitions/response.Object'
              type: object
        "401":
          description: Unauthorized
          schema:
            allOf:
            - $ref: '#/definitions/response.BodyTpl'
            - properties:
                errors:
                  $ref: '#/definitions/response.Object'
                message:
                  type: string
                status:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      tags:
      - Login Check
  /auth/register:
    post:
      consumes:
      - application/json
      description: To create a new user
      parameters:
      - description: payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/users.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.BodyTpl'
            - properties:
                message:
                  type: string
                status:
                  type: string
                values:
                  $ref: '#/definitions/response.Object'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/response.BodyTpl'
            - properties:
                errors:
                  $ref: '#/definitions/response.Object'
                message:
                  type: string
                status:
                  type: string
              type: object
      tags:
      - Register
  /health/status:
    get:
      consumes:
      - application/json
      description: To check health service
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.BodyTpl'
            - properties:
                message:
                  type: string
                status:
                  type: string
                values:
                  $ref: '#/definitions/response.Object'
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/response.BodyTpl'
            - properties:
                errors:
                  $ref: '#/definitions/response.Object'
                message:
                  type: string
                status:
                  type: string
              type: object
      tags:
      - Health
swagger: "2.0"
